// animalData.js
import sanctuary from "./assets/sanctuary.jpg";

export const animalData = {
  "Andhra Pradesh": {
    name: "Nagarjunsagar-Srisailam Tiger Reserve",
    info: "Located in the Nallamala Hills, it is the largest tiger reserve in India and home to a variety of wildlife.",
    image: sanctuary,
    coordinates: [78.8853, 16.2286],
  },
  "Arunachal Pradesh": {
    name: "Namdapha National Park",
    info: "Known for its biodiversity, including tigers, leopards, and red pandas, it is the largest protected area in the Eastern Himalayas.",
    image: sanctuary,
    coordinates: [96.3882, 27.5884],
  },
  "Assam": {
    name: "Kaziranga National Park",
    info: "A UNESCO World Heritage Site, Kaziranga is famous for its population of the Indian one-horned rhinoceros.",
    image: sanctuary,
    coordinates: [93.3631, 26.5751],
  },
  "Bihar": {
    name: "Valmiki National Park",
    info: "Located in the foothills of the Himalayas, it is home to Bengal tigers, leopards, and various other wildlife species.",
    image: sanctuary,
    coordinates: [84.1067, 27.3264],
  },
  "Chhattisgarh": {
    name: "Indravati National Park",
    info: "Known for its population of wild buffaloes, it is one of the most significant wildlife areas in central India.",
    image: sanctuary,
    coordinates: [81.1975, 19.1366],
  },
  "Goa": {
    name: "Bhagwan Mahavir Wildlife Sanctuary",
    info: "This sanctuary is famous for its rich biodiversity and is the largest in Goa.",
    image: sanctuary,
    coordinates: [74.2142, 15.2773],
  },
  "Gujarat": {
    name: "Gir National Park",
    info: "The only natural habitat of the Asiatic lion in the world.",
    image: sanctuary,
    coordinates: [70.7489, 21.1267],
  },
  "Haryana": {
    name: "Sultanpur National Park",
    info: "Known for its bird population, it is a popular destination for birdwatching.",
    image: sanctuary,
    coordinates: [76.8900, 28.4646],
  },
  "Himachal Pradesh": {
    name: "Great Himalayan National Park",
    info: "A UNESCO World Heritage Site, it hosts diverse flora and fauna within the Himalayan ranges.",
    image: sanctuary,
    coordinates: [77.5630, 31.7368],
  },
  "Jharkhand": {
    name: "Betla National Park",
    info: "One of the first national parks in India to become a tiger reserve under Project Tiger.",
    image: sanctuary,
    coordinates: [84.2184, 23.7181],
  },
  "Karnataka": {
    name: "Bandipur National Park",
    info: "Famous for its population of Bengal tigers and Indian elephants.",
    image: sanctuary,
    coordinates: [76.6186, 11.6546],
  },
  "Kerala": {
    name: "Periyar National Park",
    info: "A notable elephant and tiger reserve, it is located around the Periyar River.",
    image: sanctuary,
    coordinates: [77.1680, 9.4669],
  },
  "Madhya Pradesh": {
    name: "Kanha National Park",
    info: "A famous tiger reserve and inspiration for Rudyard Kipling's 'The Jungle Book.'",
    image: sanctuary,
    coordinates: [80.6115, 22.3345],
  },
  "Maharashtra": {
    name: "Tadoba Andhari Tiger Reserve",
    info: "One of the oldest and largest national parks in Maharashtra, known for its large tiger population.",
    image: sanctuary,
    coordinates: [79.3474, 20.2413],
  },
  "Manipur": {
    name: "Keibul Lamjao National Park",
    info: "The only floating national park in the world, home to the endangered sangai deer.",
    image: sanctuary,
    coordinates: [93.8037, 24.5035],
  },
  "Meghalaya": {
    name: "Nokrek National Park",
    info: "Known for its rich biodiversity and as a habitat for the red panda.",
    image: sanctuary,
    coordinates: [90.3154, 25.4691],
  },
  "Mizoram": {
    name: "Dampa Tiger Reserve",
    info: "Mizoram's largest protected area and home to a variety of wildlife, including tigers.",
    image: sanctuary,
    coordinates: [92.3442, 23.5009],
  },
  "Nagaland": {
    name: "Intanki National Park",
    info: "Known for its diverse wildlife and scenic landscapes.",
    image: sanctuary,
    coordinates: [93.7670, 25.8556],
  },
  "Odisha": {
    name: "Simlipal National Park",
    info: "A tiger reserve with diverse flora and fauna, including elephants and tigers.",
    image: sanctuary,
    coordinates: [86.3500, 21.9350],
  },
  "Punjab": {
    name: "Abohar Wildlife Sanctuary",
    info: "Known for its protection of the blackbuck species.",
    image: sanctuary,
    coordinates: [74.2399, 30.1457],
  },
  "Rajasthan": {
    name: "Ranthambore National Park",
    info: "One of the best places in India to see tigers in their natural habitat.",
    image: sanctuary,
    coordinates: [76.5026, 26.0173],
  },
  "Sikkim": {
    name: "Khangchendzonga National Park",
    info: "A UNESCO World Heritage Site, it covers the Khangchendzonga mountain range.",
    image: sanctuary,
    coordinates: [88.4642, 27.6036],
  },
  "Tamil Nadu": {
    name: "Mudumalai National Park",
    info: "Part of the Nilgiri Biosphere Reserve and known for its elephants and Bengal tigers.",
    image: sanctuary,
    coordinates: [76.5193, 11.5768],
  },
  "Telangana": {
    name: "Kawal Tiger Reserve",
    info: "Located in the northern part of Telangana, known for tigers, leopards, and other wildlife.",
    image: sanctuary,
    coordinates: [79.4094, 19.1811],
  },
  "Tripura": {
    name: "Sepahijala Wildlife Sanctuary",
    info: "Famous for its clouded leopards and rich biodiversity.",
    image: sanctuary,
    coordinates: [91.3878, 23.6666],
  },
  "Uttar Pradesh": {
    name: "Dudhwa National Park",
    info: "Known for its rich wildlife, including tigers, leopards, and swamp deer.",
    image: sanctuary,
    coordinates: [80.6667, 28.5016],
  },
  "Uttarakhand": {
    name: "Jim Corbett National Park",
    info: "The oldest national park in India, known for its tiger population and scenic landscapes.",
    image: sanctuary,
    coordinates: [78.7747, 29.5304],
  },
  "West Bengal": {
    name: "Sundarbans National Park",
    info: "A UNESCO World Heritage Site and famous for its population of Royal Bengal tigers.",
    image: sanctuary,
    coordinates: [88.5721, 21.9497],
  },
};
